name: freshbuyer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable_text: ^2.3.0
  graphql_flutter: ^5.1.2
  firebase_auth:
  firebase_core:
  google_sign_in:
  get_it:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/tabbar/bold/
    - assets/icons/tabbar/light/
    - assets/icons/light/
    - assets/icons/bold/
    - assets/icons/products/
    - assets/icons/profile/
    - assets/icons/detail/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700